title: MyTestCourse
description: 'This is a Test Course '
template:
  repo: mytestcourse-template
  name: mytestcourse
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
